Feat#37/change material ui version to mui version 5
buildlyio/buildly-react-template pull request #39
Opened 2022-03-14 07:13 UTC by MounikaReddy15

## Purpose
_change material-ui version from 4 to mui version 5_

## Ticket number
#37

2022-03-21 09:13 UTC, RadhikaPPatel requested changes
Get a few errors on different pages. Please handle them

![image](https://user-images.githubusercontent.com/70138493/159232398-d8afe243-1447-4dd3-a4d1-268d444a9d9c.png)

2022-03-21 09:13 UTC, RadhikaPPatel commented on src/App.js
> +import { ThemeProvider, StyledEngineProvider } from '@mui/material/styles';
Why is StyledEngineProvider needed?

2022-03-23 12:27 UTC, MounikaReddy15 commented
changes present in another pr #41

2022-03-23 12:27 UTC, MounikaReddy15 commented
changes present in another pr #41

2022-03-23 12:28 UTC, MounikaReddy15 commented
changes present in another pr #41

2022-03-23 12:28 UTC, MounikaReddy15 commented
changes present in another pr #41

2022-03-23 12:28 UTC, closed without merging